### ISSUE TITLE
Uncaught exception 'DTS\eBaySDK\Exceptions\InvalidPropertyTypeException'

### ISSUE THREAD

**Issue by rishabhsethi-it** [davidtsadler/ebay-sdk-trading#18]
Platform:
Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11 Server at localhost Port 80.

Example Git Link:
/ebay-sdk-examples/blob/master/trading/06-add-an-item-with-multiple-variations.php

Error:(No changes Made to orginal file mentioned above )

Fatal error: Uncaught exception 'DTS\eBaySDK\Exceptions\InvalidPropertyTypeException' with message 'Invalid property type: DTS\eBaySDK\Trading\Types\VariationType::VariationSpecifics expected <DTS\eBaySDK\Types\UnboundType>, got <DTS\eBaySDK\Trading\Types\NameValueListArrayType>' in C:\xampp\htdocs\ebaytrade\vendor\dts\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php:334 Stack trace: #0 C:\xampp\htdocs\ebaytrade\vendor\dts\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(265): DTS\eBaySDK\Types\BaseType->setValue('DTS\\eBaySDK\\Tra...', 'VariationSpecif...', Object(DTS\eBaySDK\Trading\Types\NameValueListArrayType)) #1 C:\xampp\htdocs\ebaytrade\vendor\dts\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(99): DTS\eBaySDK\Types\BaseType->set('DTS\\eBaySDK\\Tra...', 'VariationSpecif...', Object(DTS\eBaySDK\Trading\Types\NameValueListArrayType)) #2 C:\xampp\htdocs\ebaytrade\verify-add-an-item-with-multiple-variations.php(147): DTS\eBaySDK\Types\BaseType->__set('VariationSpecif...', Object(DTS\eBaySDK\Trading\Types\NameValueListArrayType)) #3 in C:\xampp\htdocs\ebaytrade\vendor\dts\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php on line 334

**Comment by rishabhsethi-it** [comment]
I have just Used latest copy of Example.
